# Generated by Django 5.1.4 on 2026-05-19 11:44

import django.db.models.deletion
import django_puid.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('mod', 'Moderator'), ('member', 'Member')], default='member', max_length=16)),
                ('nickname', models.CharField(blank=True, max_length=64)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-joined_at'],
            },
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puid', django_puid.fields.PrefixedUIDField(blank=True, editable=False, max_length=64, prefix='srv', random_length=10, separator='_', unique=True)),
                ('name', models.CharField(max_length=80)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='servers/icons/')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='servers/banners/')),
                ('description', models.TextField(blank=True)),
                ('is_public', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('members', models.ManyToManyField(related_name='servers', through='servers.Membership', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_servers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='membership',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servers.server'),
        ),
        migrations.AlterUniqueTogether(
            name='membership',
            unique_together={('user', 'server')},
        ),
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puid', django_puid.fields.PrefixedUIDField(blank=True, editable=False, max_length=64, prefix='chn', random_length=10, separator='_', unique=True)),
                ('name', models.CharField(max_length=80)),
                ('slug', models.SlugField(max_length=80)),
                ('kind', models.CharField(choices=[('text', 'Text'), ('announcement', 'Announcement'), ('voice', 'Voice (placeholder)')], default='text', max_length=16)),
                ('topic', models.CharField(blank=True, max_length=240)),
                ('position', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channels', to='servers.server')),
            ],
            options={
                'ordering': ['position', 'name'],
                'unique_together': {('server', 'slug')},
            },
        ),
    ]
